services:
  app:
    volumes:
      - ./laravel-app:/var/www/html

  queue:
    volumes:
      - ./laravel-app:/var/www/html

  scheduler:
    volumes:
      - ./laravel-app:/var/www/html

  reverb:
    volumes:
      - ./laravel-app:/var/www/html
